"""Render skill schema references from Pydantic models."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from .schema_models import CatalogExtractionRecord, CatalogReviewRecord, LiteratureHvsCandidatesRecord


def _schema_for(model: type[BaseModel]) -> dict[str, Any]:
    return model.model_json_schema(mode="validation")


def _properties(schema: dict[str, Any]) -> dict[str, Any]:
    value = schema.get("properties")
    return value if isinstance(value, dict) else {}


def _required(schema: dict[str, Any]) -> list[str]:
    value = schema.get("required")
    return [str(item) for item in value] if isinstance(value, list) else []


def _json_block(value: Any) -> str:
    return "```json\n" + json.dumps(value, ensure_ascii=False, indent=2) + "\n```"


def render_model_schema_doc(
    *,
    title: str,
    model: type[BaseModel],
    purpose: str,
    workflow_notes: list[str],
) -> str:
    schema = _schema_for(model)
    properties = _properties(schema)
    required = _required(schema)
    lines = [
        f"# `{title}` Schema",
        "",
        "<!-- Generated by scripts/generate_schema_docs.py; do not edit by hand. -->",
        "",
        purpose,
        "",
        f"Use `schema_version: \"{schema.get('properties', {}).get('schema_version', {}).get('const', '')}\"`.",
        "",
        "## Required Top-Level Fields",
        "",
    ]
    for field in required:
        lines.append(f"- `{field}`")
    enum_values = _enum_values(schema)
    lines.extend(["", "## Top-Level Shape", "", _json_block(_top_level_template(properties)), ""])
    if enum_values:
        lines.extend(["## Enum Values", ""])
        for value in enum_values:
            lines.append(f"- `{value}`")
        lines.append("")
    if workflow_notes:
        lines.extend(["## Workflow Notes", ""])
        for note in workflow_notes:
            lines.append(f"- {note}")
        lines.append("")
    lines.extend(["## JSON Schema", "", _json_block(schema), ""])
    return "\n".join(lines)


def _top_level_template(properties: dict[str, Any]) -> dict[str, Any]:
    template: dict[str, Any] = {}
    for field, spec in properties.items():
        if field == "schema_version":
            template[field] = spec.get("const", "")
        elif spec.get("type") == "array":
            template[field] = []
        elif spec.get("type") == "object" or "$ref" in spec:
            template[field] = {}
        else:
            template[field] = ""
    return template


def _enum_values(node: Any) -> list[str]:
    values: set[str] = set()

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            enum = value.get("enum")
            if isinstance(enum, list):
                values.update(str(item) for item in enum)
            const = value.get("const")
            if isinstance(const, str):
                values.add(const)
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    walk(node)
    return sorted(values)


def generated_schema_docs() -> dict[Path, str]:
    return {
        Path("skills/hvs-catalog-review/references/schema.md"): render_model_schema_doc(
            title="catalog_review.json",
            model=CatalogReviewRecord,
            purpose=(
                "`catalog_review.json` is the Agent-filled data-asset inventory for one archived paper. "
                "The template and accepted fields come from the Pydantic model; the Agent fills only "
                "paper-grounded semantic blanks such as table roles, column meanings, evidence, and comments."
            ),
            workflow_notes=[
                "Generate a skeleton with `scripts/init_catalog_review.py --arxiv-id <arxiv_id>` before Agent filling.",
                "Do not add fields outside the generated schema; validators reject undeclared keys.",
                "Use `scripts/validate_catalog_review.py --require-complete` for final Agent-filled output; plain validation only checks structural skeleton validity.",
                "This stage does not convert tables to ECSV and does not decide HVS candidate inclusion.",
            ],
        ),
        Path("skills/hvs-catalog-extraction/references/schema.md"): render_model_schema_doc(
            title="catalog_extraction.json",
            model=CatalogExtractionRecord,
            purpose=(
                "`catalog_extraction.json` is generated by `scripts/extract_catalog_tables.py` from "
                "`catalog_review.json`. Agent code should not hand-fill this file."
            ),
            workflow_notes=[
                "The extractor validates the manifest against this schema before writing it.",
                "Use `scripts/validate_catalog_extraction.py --require-reviewed` for final workflow checks.",
                "External resources from review are not represented in extraction output.",
                "Converter stdout/stderr contents stay in artifact files; JSON stores only artifact paths.",
            ],
        ),
        Path("skills/hvs-candidates-extraction/references/schema.md"): render_model_schema_doc(
            title="literature_hvs_candidates.json",
            model=LiteratureHvsCandidatesRecord,
            purpose=(
                "`literature_hvs_candidates.json` is the Agent-filled paper-level HVS/unbound candidate "
                "fact source. Generate a skeleton from code, then fill candidate semantics and provenance."
            ),
            workflow_notes=[
                "Generate a skeleton with `scripts/init_hvs_candidates.py --arxiv-id <arxiv_id>` after review and extraction exist.",
                "Candidate inclusion is driven by paper text, not by tables alone.",
                "Use `scripts/validate_hvs_candidates.py --require-complete` for final Agent-filled output; plain validation only checks structural skeleton validity.",
                "Every quantity must preserve `raw_value`, cleaned `value`, source references, and exactly one direct-producer `method_refs` entry when complete.",
                "Candidate identifiers live under `identifiers`: `record_id` is the internal `<arxiv_id>:cand-001` record key, `paper_candidate_id` is the paper display name, `gaia_source_id` is the strict Gaia machine id or empty string, and `all[]` stores paper-visible names with source refs.",
                "For numeric core fields and quantitative typed records, `value`, `error`, `lower_error`, and `upper_error` should be single plain numbers; ranges, limits, units, notes, and LaTeX residue stay in `raw_value`/`description`.",
                "`core.bound_assessment.bound_probability` and `unbound_probability` normalize `value` to a unitless 0-1 fraction and leave `unit` empty; paper percent values remain in `raw_value` and source refs.",
                "RA/Dec are coordinate records: keep each coordinate component in `raw_value`/`value`, put frame and epoch context in the nested `reference_frame` and `epoch` objects, and use `component_raw_value` when one ECSV cell contains both components.",
                "`method_chain[]` uses local `step-XX` ids, canonical `step_type` values, and `depends_on[]` to encode upstream method lineage.",
                "Full quantity provenance is the direct `method_refs` step plus recursive `depends_on[]` ancestors; candidates do not carry paper-level `method_chain_refs`.",
                "The standard `core` groups are `observed_phase_space`, `derived_kinematics`, and `bound_assessment`; photometry, spectroscopy, stellar parameters, abundances, quality flags, orbit values, and origin metrics use typed candidate groups before `extra[]`.",
            ],
        ),
    }
