"""Render skill schema references from Pydantic models."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from .schema_models import (
    CatalogExtractionRecord,
    CatalogReviewRecord,
    LiteratureHvsCandidatesRecord,
)
from .hvs_contribution_models import LiteratureHvsContributionsRecord


def _schema_for(model: type[BaseModel]) -> dict[str, Any]:
    return model.model_json_schema(mode="validation")


def _properties(schema: dict[str, Any]) -> dict[str, Any]:
    value = schema.get("properties")
    return value if isinstance(value, dict) else {}


def _required(schema: dict[str, Any]) -> list[str]:
    value = schema.get("required")
    return [str(item) for item in value] if isinstance(value, list) else []


def _json_block(value: Any) -> str:
    return "```json\n" + json.dumps(value, ensure_ascii=False, indent=2) + "\n```"


def _schema_identity(schema: dict[str, Any]) -> dict[str, Any]:
    ref = _properties(schema).get("schema", {}).get("$ref", "")
    target: Any = schema
    for part in str(ref).removeprefix("#/").split("/") if ref else ():
        target = target.get(part, {}) if isinstance(target, dict) else {}
    properties = _properties(target) if isinstance(target, dict) else {}
    return {
        "name": properties.get("name", {}).get("const", ""),
        "version": properties.get("version", {}).get("const", 0),
    }


def render_model_schema_doc(
    *,
    title: str,
    model: type[BaseModel],
    purpose: str,
    workflow_notes: list[str],
) -> str:
    schema = _schema_for(model)
    properties = _properties(schema)
    required = _required(schema)
    identity = _schema_identity(schema)
    lines = [
        f"# `{title}` Schema",
        "",
        "<!-- Generated by scripts/generate_schema_docs.py; do not edit by hand. -->",
        "",
        purpose,
        "",
        f"Use `schema: {json.dumps(identity, separators=(',', ':'))}`.",
        "",
        "## Required Top-Level Fields",
        "",
    ]
    for field in required:
        lines.append(f"- `{field}`")
    enum_values = _enum_values(schema)
    lines.extend(["", "## Top-Level Shape", "", _json_block(_top_level_template(properties)), ""])
    if enum_values:
        lines.extend(["## Enum Values", ""])
        for value in enum_values:
            lines.append(f"- `{value}`")
        lines.append("")
    if workflow_notes:
        lines.extend(["## Workflow Notes", ""])
        for note in workflow_notes:
            lines.append(f"- {note}")
        lines.append("")
    lines.extend(["## JSON Schema", "", _json_block(schema), ""])
    return "\n".join(lines)


def _top_level_template(properties: dict[str, Any]) -> dict[str, Any]:
    template: dict[str, Any] = {}
    for field, spec in properties.items():
        if field == "schema":
            template[field] = {}
        elif spec.get("type") == "array":
            template[field] = []
        elif spec.get("type") == "object" or "$ref" in spec:
            template[field] = {}
        else:
            template[field] = ""
    return template


def _enum_values(node: Any) -> list[str]:
    values: set[str] = set()

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            enum = value.get("enum")
            if isinstance(enum, list):
                values.update(str(item) for item in enum)
            const = value.get("const")
            if isinstance(const, str):
                values.add(const)
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    walk(node)
    return sorted(values)


def generated_schema_docs() -> dict[Path, str]:
    return {
        Path("skills/hvs-catalog-review/references/schema.md"): render_model_schema_doc(
            title="catalog_review.json",
            model=CatalogReviewRecord,
            purpose=(
                "`catalog_review.json` is the Agent-filled data-asset inventory for one archived paper. "
                "The template and accepted fields come from the Pydantic model; the Agent fills only "
                "paper-grounded semantic blanks such as table roles, column meanings, evidence, and comments."
            ),
            workflow_notes=[
                "Generate a skeleton with `scripts/init_catalog_review.py --arxiv-id <arxiv_id>` before Agent filling.",
                "Do not add fields outside the generated schema; validators reject undeclared keys.",
                "Use `scripts/validate_catalog_review.py --require-complete` for final Agent-filled output; plain validation only checks structural skeleton validity.",
                "This stage does not convert tables to ECSV and does not decide HVS candidate inclusion.",
            ],
        ),
        Path("skills/hvs-catalog-extraction/references/schema.md"): render_model_schema_doc(
            title="catalog_extraction.json",
            model=CatalogExtractionRecord,
            purpose=(
                "`catalog_extraction.json` is generated by `scripts/extract_catalog_tables.py` from "
                "`catalog_review.json`. Agent code should not hand-fill this file."
            ),
            workflow_notes=[
                "The extractor validates the manifest against this schema before writing it.",
                "Use `scripts/validate_catalog_extraction.py --require-reviewed` for final workflow checks.",
                "External resources from review are not represented in extraction output.",
                "Converter stdout/stderr contents stay in artifact files; JSON stores only artifact paths.",
            ],
        ),
        Path("skills/hvs-candidates-extraction/references/schema.md"): render_model_schema_doc(
            title="literature_hvs_candidates.json",
            model=LiteratureHvsCandidatesRecord,
            purpose=(
                "`literature_hvs_candidates.json` is the canonical v3 core-first "
                "HVS candidate artifact generated from an immutable extraction run."
            ),
            workflow_notes=[
                "Candidate inclusion is frozen by the roster stage before field extraction.",
                "Every non-null numeric component carries direct evidence; context evidence establishes meaning, frame, scenario, or group conditions.",
                "A field-stage failure preserves the candidate with field_status=field_extraction_failed and a nullable 19-field core.",
                "The v3 artifact contains no full-field enrichment or method-chain data; those belong to separately hashed supplements.",
            ],
        ),
        Path("skills/hvs-candidates-extraction/references/contributions-schema.md"): render_model_schema_doc(
            title="literature_hvs_contributions.json",
            model=LiteratureHvsContributionsRecord,
            purpose=(
                "`literature_hvs_contributions.json` is the canonical v1 contribution-first "
                "HVS artifact: one record per current-paper/object contribution. It is "
                "parallel to the V6 `literature_hvs_candidates` pipeline and pre-campaign: "
                "no formal benchmark campaign is bound to it yet."
            ),
            workflow_notes=[
                "The canonical unit is the paper-object contribution, not final unbound-candidate membership; bound reassessments stay included as follow_up contributions.",
                "Every included object requires a non-empty contribution_summary and at least one contribution_evidence locator into the current paper.",
                "paper_boundness is the paper's own object-level summary with exactly five statuses and is never derived from a probability or threshold.",
                "Quantities group every structured numeric quantity reported or adopted by the paper as unordered multisets; exact duplicate full records are rejected.",
                "A roster-success/quantity-failure object survives with quantity_extraction_status=failed, empty quantities, and an explicit failure object.",
                "record_id is a program-generated document-local handle; identifiers are an unordered evidence-bearing list and are used only for object pairing.",
            ],
        ),
    }


def assert_generated_schema_docs_current(workspace: Path) -> None:
    stale = [
        path
        for path, content in generated_schema_docs().items()
        if not (workspace / path).is_file()
        or (workspace / path).read_text(encoding="utf-8") != content
    ]
    if stale:
        joined = ", ".join(str(path) for path in stale)
        raise RuntimeError(
            "generated schema references are stale; run "
            f"scripts/generate_schema_docs.py: {joined}"
        )
